version: '3.3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000
    volumes:
      - data:/usr/share/app/data
    networks:
      - my_network
    env_file:
      - ./env-file.env
    deploy:
      replicas: 3
volumes:
  data: {}
networks:
  my_network:
    driver: bridge
